1.6.0 Modification for mixer-layout
voxeet/voxeet-uxkit-web-mixerlayout pull request #11
Opened 2021-04-23 12:15 UTC by Energizz

2021-04-23 12:34 UTC, f-ld approved these changes
lgtm

2021-04-26 16:03 UTC, FabienLavocat requested changes

2021-04-26 16:03 UTC, FabienLavocat commented on README.md
> +   <input
I would use a one-liner here to keep consistency with the other input elements

2021-04-26 16:03 UTC, FabienLavocat commented on README.md
> +   <button
I would use a one-liner here to keep consistency with the other button above.

2021-04-26 16:03 UTC, FabienLavocat commented on README.md
> +   <input
I would use a one-liner here to keep consistency with the other input elements

2021-04-26 16:03 UTC, FabienLavocat commented on package.json
> +    "build": "npx webpack  --output-filename out.js --output-path dist"
Extra space added

2021-04-26 16:03 UTC, FabienLavocat commented on src/app/components/ConferenceRoom.js
> -    let className = "tiles-list";
the line 262 in this file need to be updated from:
```
{(consumerKey == null || consumerKey == null) && (
```
to:
```
{(consumerKey == null || consumerSecret == null) && (
```

2021-04-26 16:03 UTC, FabienLavocat commented on src/app/components/ConferenceRoom.js
>      const { isLaunch, layoutType } = this.state;
`layoutType` is never used

2021-04-26 16:03 UTC, FabienLavocat commented on src/app/components/ConferenceRoom.js
> +                  placeholder="Conference name"
Maybe `Conference alias`?

2021-04-26 16:03 UTC, FabienLavocat commented on src/app/components/ConferenceRoom.js
>      return (
Could we change the title of this page (in the h1 tag) to `Dolby Mixer Layout Testing`

2021-04-26 16:03 UTC, FabienLavocat commented on src/app/actions/ConferenceActions.js
>                    audio3D: false,
Should we remove that `audio3D`?

2021-04-27 12:17 UTC, Energizz commented on src/app/components/ConferenceRoom.js
>      return (
Of course :)

2021-04-27 14:30 UTC, FabienLavocat approved these changes
Thanks :)

2021-04-27 15:09 UTC, merged